Updated CI to deploy to Statiko too

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -1,4 +1,12 @@
-# CI pipelines for Azure Pipelines, using Hugo
+# Required variables:
+# NODE_ADDRESS: Address (IP or hostname) of the Statiko node to connect to (must be able to accept connections on port 2265 from the Azure Pipelines agent)
+# NODE_KEY (secret): pre-shared key for authenticating with the Statiko node
+# PINATA_API_KEY: API key for Pinata
+# PINATA_SECRET_KEY (secret): Secret key for Pinata
+# CLOUDFLARE_ZONE_ID: ID of the Cloudflare zone
+# CLOUDFLARE_API_TOKEN (secret): API token for updating the DNS zone on Cloudflare
+
+# Site is published on both the Statiko platform and on IPFS (via Pinata)
 
 # Define repository
 resources:
@@ -10,12 +18,15 @@ trigger:
 
 # Variables for the entire pipeline
 variables:
-  # Version of Hugo
-  HUGO_VERSION: 0.60.1
-  # Version of Pinata Pinner
-  PINATAPINNER_VERSION: 0.1.1
-  # Domain to update (DNSLink)
+  # Sites
+  SITE_PRODUCTION: 'withblue.ink'
+  SITE_STAGING: 'staging.withblue.ink'
+  # Azure connection ID
+  AZURE_SERVICE_CONNECTION: '2ac418d2-f0b4-4d6f-be85-f4998ea75559'
+  # DNSLink DNS record to update (for IPFS)
   CLOUDFLARE_DOMAIN: '_dnslink.withblue.ink'
+  # Version of Hugo to use
+  HUGO_VERSION: 0.60.1
 
 # Stages
 stages:
@@ -38,9 +49,9 @@ stages:
 
           # Install Node.js first, which is necessary for the module depdendencies
           - task: NodeTool@0
-            displayName: 'Use Node.js 10.x'
+            displayName: 'Use Node.js 12.x'
             inputs:
-              versionSpec: 10.x
+              versionSpec: 12.x
 
           # Install Hugo
           - script: |
@@ -71,60 +82,83 @@ stages:
         environment: Staging
         displayName: 'Stage app'
 
-        # Run on Linux (Ubuntu 18.04)
+        # Run on the self-hosted agent in the LAN
         pool:
-          vmImage: 'Ubuntu-18.04'
-        
+          name: Default
+          demands:
+            - network -equals lacasetta
+
         # Deployment strategy is "runOnce"
         strategy:
           runOnce:
             deploy:
               # Steps
               steps:
+                # Do not checkout source
+                - checkout: none
+
                 # Download pipeline artifact
                 - download: current
                   artifact: 'public'
 
-                # Copy files to staging via SSH
-                - task: CopyFilesOverSSH@0
-                  displayName: 'Copy files to staging via SSH'
-                  inputs:
-                    sshEndpoint: 'IPFS-EU'
-                    sourceFolder: '$(Pipeline.Workspace)/public'
-                    targetFolder: '/data/ipfs-staging/withblueink'
-                    cleanTargetFolder: true
-                    failOnEmptySource: true
+                # Install stkcli
+                - bash: |
+                    set -e
+                    URL=$(curl -s https://api.github.com/repos/ItalyPaleAle/stkcli/releases/latest -H "Accept: application/vnd.github.v3+json" \
+                      | jq -r ".assets[] | select(.name | test(\"linux_arm32v7\")) | .browser_download_url")
+                    echo "Downloading stkcli: $URL"
+                    curl -L "$URL" -o stkcli
+                    chmod +x stkcli
+                    ./stkcli version
+                  displayName: "Install stkcli"
 
-                # Pin files on IPFS
-                - task: SSH@0
-                  name: pinfiles
-                  displayName: 'Pin files on IPFS'
+                # Install pinatapinner
+                - bash: |
+                    set -e
+                    URL=$(curl -s https://api.github.com/repos/ItalyPaleAle/pinatapinner/releases/latest -H "Accept: application/vnd.github.v3+json" \
+                      | jq -r ".assets[] | select(.name | test(\"linux_arm\")) | .browser_download_url")
+                    echo "Downloading pinatapinner: $URL"
+                    curl -L "$URL" -o pinatapinner
+                    chmod +x pinatapinner
+                  displayName: "Install pinatapinner"
+
+                # Deploy app to staging on Statiko (with Azure CLI authorization)
+                - task: AzureCLI@2
+                  displayName: 'Deploy app to staging on Statiko'
                   inputs:
-                    sshEndpoint: 'IPFS-EU'
-                    runOptions: inline
-                    inline: |
+                    azureSubscription: $(AZURE_SERVICE_CONNECTION)
+                    scriptType: 'bash'
+                    scriptLocation: 'inlineScript'
+                    inlineScript: |
                       set -e
-                      
-                      # Add files to IPFS
-                      IPFS_HASH=$(sudo docker exec ipfs-node ipfs add -rQ /staging/withblueink)
-                      echo "IPFS hash: ${IPFS_HASH}"
 
-                      # Set the IPFS_HASH variable
-                      echo "##vso[task.setvariable variable=IPFS_HASH]$IPFS_HASH"
+                      # Get version from Azure Pipelines
+                      echo "Version: $(Build.BuildNumber)"
 
-                      # Add to the pinset of the cluster
-                      #sudo docker exec ipfs-cluster ipfs-cluster-ctl pin add $IPFS_HASH
+                      echo "Folder: $(Pipeline.Workspace)/public"
+                      ls -l $(Pipeline.Workspace)/public
+
+                      # Upload the app
+                      export NODE_KEY="$(NODE_KEY)"
+                      ./stkcli upload app \
+                        -n $(NODE_ADDRESS) \
+                        -k \
+                        -a withblueink \
+                        -v $(Build.BuildNumber) \
+                        -f $(Pipeline.Workspace)/public
+
+                      # Deploy to staging
+                      ./stkcli deploy \
+                        -n $(NODE_ADDRESS) \
+                        -k \
+                        -d $(SITE_STAGING) \
+                        -a withblueink \
+                        -v $(Build.BuildNumber)
 
                 # Pin on Pinata
                 - script: |
                     set -e
-                    
-                    # Download pinatapinner
-                    sudo curl -L "https://github.com/ItalyPaleAle/pinatapinner/releases/download/v$(PINATAPINNER_VERSION)/pinatapinner_linux_amd64" -o /usr/local/bin/pinatapinner
-                    sudo chmod +x /usr/local/bin/pinatapinner
-                    
-                    # Pin on Pinata
-                    pinatapinner $(Pipeline.Workspace)/public "WithBlueInk-${BUILD_BUILDID}"
+                    ./pinatapinner $(Pipeline.Workspace)/public "WithBlueInk-${BUILD_BUILDID}"
                   displayName: 'Pin on Pinata'
                   env:
                     PINATA_API_KEY: $(PINATA_API_KEY)
@@ -142,6 +176,17 @@ stages:
                   artifact: variables
                   displayName: 'Publish pipeline artifacts'
 
+                # Post-build cleanup
+                # Necessary only for self-hosted pipelines
+                - bash: |
+                    # Delete files from disk
+                    rm -rvf $(Agent.BuildDirectory) || true
+                    rm -rvf $(Build.SourcesDirectory) || true
+                    rm -rvf $(Build.ArtifactStagingDirectory) || true
+                  displayName: "Post-build cleanup"
+                  # This step always runs, even if the pipeline failed
+                  condition: always()
+
   # Deploy to production stage
   - stage: production
     displayName: 'Deploy to production'
@@ -152,22 +197,39 @@ stages:
         environment: Production
         displayName: 'Deploy to production'
 
-        # Run on Linux (Ubuntu 18.04)
+        # Run on the self-hosted agent in the LAN
         pool:
-          vmImage: 'Ubuntu-18.04'
-        
+          name: Default
+          demands:
+            - network -equals lacasetta
+
         # Deployment strategy is "runOnce"
         strategy:
           runOnce:
             deploy:
               # Steps
               steps:
+                # Do not checkout source
+                - checkout: none
+
                 # Download the variables artifact
                 - download: current
                   artifact: variables
                   displayName: 'Download pipeline artifacts'
 
-                # Update DNS record
+                # Deploy app to production on Statiko
+                - script: |
+                    set -e
+                    ./stkcli deploy \
+                      -n $(NODE_ADDRESS) \
+                      -k \
+                      -d $(SITE_PRODUCTION) \
+                      -a withblueink -v $(Build.BuildNumber)
+                  displayName: 'Deploy app to production on Statiko'
+                  env:
+                    NODE_KEY: $(NODE_KEY)
+
+                # Update DNSLink record
                 - script: |
                     set -e
 
@@ -186,4 +248,15 @@ stages:
                           -H "Content-Type:application/json" \
                           -H "Authorization:Bearer $(CLOUDFLARE_API_TOKEN)" \
                           --data "{\"type\":\"TXT\",\"name\":\"$(CLOUDFLARE_DOMAIN)\",\"content\":\"dnslink=/ipfs/$IPFS_HASH\",\"ttl\":120,\"priority\":10,\"proxied\":false}"
-                  displayName: 'Update DNS record'
+                  displayName: 'Update DNSLink record'
+
+                # Post-build cleanup
+                # Necessary only for self-hosted pipelines
+                - bash: |
+                    # Delete files from disk
+                    rm -rvf $(Agent.BuildDirectory) || true
+                    rm -rvf $(Build.SourcesDirectory) || true
+                    rm -rvf $(Build.ArtifactStagingDirectory) || true
+                  displayName: "Post-build cleanup"
+                  # This step always runs, even if the pipeline failed
+                  condition: always()
